language: ruby

before_install:
- gem update --system
- gem install bundler

rvm:
  - 2.6.1

gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
